# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "jazz"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Florian Schade"]
  s.date = "2011-12-14"
  s.email = "f.schade@purpled.de"
  s.executables = ["jazz"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "bin/jazz",
    "dist/hashchange/jquery.ba-hashchange.js",
    "dist/jazz/lib/controller.js",
    "dist/jazz/lib/db.js",
    "dist/jazz/lib/helper.js",
    "dist/jazz/lib/model.js",
    "dist/jazz/lib/route.js",
    "dist/jazz/lib/view.js",
    "dist/jazz/main.js",
    "dist/jquery/jquery.js",
    "dist/mustache/mustache.js",
    "dist/require/order.js",
    "dist/require/require.js",
    "dist/underscore/underscore.js",
    "lib/jazz.rb",
    "lib/jazz/app_detector.rb",
    "lib/jazz/app_generator.rb",
    "lib/jazz/cli.rb",
    "lib/jazz/controller_generator.rb",
    "lib/jazz/model_generator.rb",
    "lib/jazz/scaffold_generator.rb",
    "templates/app_root/app/assets/javascripts/application.js",
    "templates/app_root/app/assets/stylesheets/application.css",
    "templates/app_root/config/glue.js",
    "templates/app_root/config/routes.js",
    "templates/application.js",
    "templates/controller.js",
    "templates/db.js",
    "templates/index.html",
    "templates/model.js",
    "templates/scaffold_controller.js"
  ]
  s.homepage = "http://github.com/f.schade@purpled.de/jazz"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "A lightweight javascript MVC framework."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

